controller_manager:
  ros__parameters:
    update_rate: 30  # Hz

    rrr_position_controller: #-------
      type: forward_command_controller/ForwardCommandController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

rrr_position_controller: #---------
  ros__parameters:
    joints:
      - shoulder_joint
      - arm_joint
      - forearm_joint
    interface_name: position