controller_manager:
  ros__parameters:
    update_rate: 100 #Hz
    rrr_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
 
rrr_trajectory_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

    joints:
      - shoulder_joint
      - arm_joint
      - forearm_joint

    state_publish_rate: 50.0
    action_monitor_rate: 20.0

    allow_partial_joints_goal: false
    allow_nonzero_velocity_at_trajectory_end: false
    open_loop_control: true
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0
      joint1:
        trajectory: 0.05
        goal: 0.03